<?php

namespace Lam\MdlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    
  public function listestageinfo($num)
  {
      $req = $this->createQueryBuilder('f')
              ->addSelect('i')
            ->join('f.lesIntervenants','i')
            ->where("f.laFormationInformatique = :num")
            ->setParameter('num', $num);
          return $req->getQuery()->getResult();
 
 /*     
  $req = $this->_em->createQueryBuilder();
        $req->select('f')
            ->from('LamMdlBundle:formation', 'f')
            ->where("f.laFormationInformatique = :num")
            ->setParameter('num', $num);
          return $req->getQuery()->getResult();
 
 */
  }
  

    public function listestagesport($num)
    {
           $req = $this->createQueryBuilder('f')
              ->addSelect('i')
            ->join('f.lesIntervenants','i')
            ->where("f.laFormationSport = :num")
            ->setParameter('num', $num);
          return $req->getQuery()->getResult();
  }
    
    
}