<?php

namespace Lam\MdlBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;

/**
 * FormationInformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationInformatiqueRepository extends EntityRepository
{
  public function listeFormationInformatique()
  {
        // On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
        $req = $this->_em->createQueryBuilder();
        $req->select('fi')
            ->from('LamMdlBundle:formationinformatique', 'fi');
        
          return $req->getQuery()->getResult();
  }
    
    public function contenuFormationInformatique($num)
    {
    $query = $this->_em->createQuery("SELECT fi.Logo,fi.Titre, fi.id toto,fi.Objectif,fi.Public,fi.Prerequis, fi.nbPlace,t.NomTheme, c.Ordre, d.Libelle FROM LamMdlBundle:contenu c JOIN c.laFormationInformatique fi JOIN c.leTheme t  LEFT JOIN c.lesDetails d where c.laFormationInformatique='$num' order by c.Ordre");
    $resultats = $query->getResult();
    return $resultats;
  }
    
    
}